postgres:
  username: ${DATABASE_POSTGRES_USERNAME:root}
  password: ${DATABASE_POSTGRES_PASSWORD:root}
  url: ${DATABASE_POSTGRES_URL:localhost:5433}
  database: ${DATABASE_POSTGRES_SCHEMA:db_codeflix_admin_catalog}

# Twelve Factors, regras para configs de produção (pesquisar)

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none